### ISSUE TITLE
Unit Testに失敗する。

### ISSUE THREAD

**Issue by kentaro000** [Personal-Data-Linkage-Module/pxr-access-control-manage-service#8]
``` npm run test:unit```を実行すると、テストに失敗する。

```
$ npm run test:unit

> access-control-manage-service@1.0.0 test:unit D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service
> jest --coverage --forceExit --detectOpenHandles --runInBand --config=jest.unit.config.js

FAIL src/tests/CreateStoreAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateShareTempAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateShareContinuousAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateSettingAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateOperatorAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateJoinAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateBookAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateCatalogAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateBlockAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateAppWfUserAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateAPIKey.validator.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

FAIL src/tests/CreateActorAPIKey.spec.ts
  ● Test suite failed to run

    ENOENT: no such file or directory, open 'D:\Users\1134142010033\Desktop\pxr-source-oss\pxr-access-control-manage-service\config\default-raw.crt'

      13 |
      14 | const allowAccessConfig = JSON.parse(fs.readFileSync(path.resolve('./config/allow-access.json'), 'utf-8'));
    > 15 | const defaultRawCertificate = fs.readFileSync(path.resolve('./config/default-raw.crt'), 'utf-8');
         |                                  ^
      16 | export default async function checkCertificateRequest (req: express.Request, dto: CreateAPIKeyReqDto[], operator: OperatorDomain) {
      17 |     if (process.env.NODE_ENV === 'test' || req.protocol === 'http') {
      18 |         return;

      at Object.<anonymous> (src/common/CheckCertificateRequest.ts:15:34)
      at Object.<anonymous> (src/resources/CreateBlockAPIKeyController.ts:16:1)

-------------------------------------------|---------|----------|---------|---------|-------------------
File                                       | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s
-------------------------------------------|---------|----------|---------|---------|-------------------
All files                                  |       0 |        0 |       0 |       0 |
 domains                                   |       0 |      100 |       0 |       0 |
  ActorCatalogDomain.ts                    |       0 |      100 |       0 |       0 | 6-69
  BlockCatalogDomain.ts                    |       0 |      100 |       0 |       0 | 6-75
  MyBookListElement.ts                     |       0 |      100 |       0 |       0 | 5-40
  NumberCToken.ts                          |       0 |      100 |       0 |       0 | 6-71
  SharingCatalog.ts                        |       0 |      100 |       0 |       0 | 6-73
  SharingDataDefinition.ts                 |       0 |      100 |       0 |       0 | 6-53
  SharingRestrintionCatalog.ts             |       0 |      100 |       0 |       0 | 6-131
  TemporarySharingDataDefinition.ts        |       0 |      100 |       0 |       0 | 6-74
 repositories                              |       0 |      100 |       0 |       0 |
  EntityOperation.ts                       |       0 |      100 |       0 |       0 | 6-33
 repositories/postgres                     |       0 |      100 |       0 |       0 |
  CallerRole.ts                            |       0 |      100 |       0 |       0 | 5-53
  TokenAccessHistory.ts                    |       0 |      100 |       0 |       0 | 5-69
  TokenGenerationHistory.ts                |       0 |      100 |       0 |       0 | 5-111
 resources                                 |       0 |        0 |       0 |       0 |
  CreateActorAPIKeyController.ts           |       0 |        0 |       0 |       0 | 7-77
  CreateAppWfUserAPIKeyController.ts       |       0 |        0 |       0 |       0 | 7-77
  CreateBlockAPIKeyController.ts           |       0 |        0 |       0 |       0 | 7-74
  CreateBookAPIKeyController.ts            |       0 |        0 |       0 |       0 | 7-80
  CreateCatalogAPIKeyController.ts         |       0 |        0 |       0 |       0 | 7-108
  CreateJoinAPIKeyController.ts            |       0 |        0 |       0 |       0 | 7-77
  CreateOperatorAPIKeyController.ts        |       0 |        0 |       0 |       0 | 7-80
  CreateSettingAPIKeyController.ts         |       0 |        0 |       0 |       0 | 7-80
  CreateShareContinuousAPIKeyController.ts |       0 |        0 |       0 |       0 | 7-157
  CreateShareTempAPIKeyController.ts       |       0 |        0 |       0 |       0 | 7-131
  CreateStoreAPIKeyController.ts           |       0 |        0 |       0 |       0 | 7-101
 resources/dto                             |       0 |      100 |       0 |       0 |
  CreateAPIKeyReqDto.ts                    |       0 |      100 |       0 |       0 | 5-120
  CreateShareContinuousAPIKeyReqDto.ts     |       0 |      100 |       0 |       0 | 6-123
  CreateShareTempAPIKeyReqDto.ts           |       0 |      100 |       0 |       0 | 6-96
 resources/validator                       |       0 |        0 |       0 |       0 |
  BaseValidator.ts                         |       0 |        0 |       0 |       0 | 9-79
  CreateBlockAPIKeyValidator.ts            |       0 |        0 |       0 |       0 | 11-31
  CreateShareContinuousAPIKeyValidator.ts  |       0 |        0 |       0 |       0 | 6-27
  CreateShareTempAPIKeyValidator.ts        |       0 |        0 |       0 |       0 | 6-27
  CreateStoreAPIKeyValidator.ts            |       0 |        0 |       0 |       0 | 11-36
 services                                  |       0 |        0 |       0 |       0 |
  AccessControlService.ts                  |       0 |        0 |       0 |       0 | 8-133
  BookManageService.ts                     |       0 |        0 |       0 |       0 | 7-122
  CTokenLedgerService.ts                   |       0 |        0 |       0 |       0 | 5-76
  CatalogService.ts                        |       0 |        0 |       0 |       0 | 6-206
  CreateAPIKeyService.ts                   |       0 |        0 |       0 |       0 | 9-545
  IdService_Stub.ts                        |       0 |      100 |       0 |       0 | 8-15
  SharingDataService.ts                    |       0 |        0 |       0 |       0 | 6-339
 services/dto                              |       0 |      100 |     100 |       0 |
  AccessControllerResult.ts                |       0 |      100 |     100 |       0 | 5-22
-------------------------------------------|---------|----------|---------|---------|-------------------
Test Suites: 12 failed, 12 total
Tests:       0 total
Snapshots:   0 total
Time:        26.309 s
Ran all test suites.
(node:19848) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 message listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
jest-html-reporter >> Report generated (./coverage-unit/report.html)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! access-control-manage-service@1.0.0 test:unit: `jest --coverage --forceExit --detectOpenHandles --runInBand --config=jest.unit.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the access-control-manage-service@1.0.0 test:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     D:\Users\1134142010033\AppData\Roaming\npm-cache\_logs\2023-10-12T05_10_52_257Z-debug.log

```

**Comment by kentaro000** [comment]
ビルド手順書の証明書作成の手順を見落としておりました。

解決済みのため、Closeして問題ありません。

**Comment by smit-akiyama** [comment]
こちらのissueは、手順書に記載された手順を見落としていたとのことで、UT実行できることも確認できておりますのでクローズいたします。
